services:
  - type: web
    name: text-summarizer
    env: python
    rootDir: Source Code
    buildCommand: pip install -r requirements.txt && python download_nltk.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
